### PR TITLE
Suggested fixes after testing this on chat.zulip.org

### PR DESCRIPTION
**Pull request by timabbott**

### CODE REVIEW

**Comment by timabbott** [comment]
@robertylewis these should be easy fixes to merge.

I also wanted to ask if you'd be OK with transferring this project to zulip/zulip_archive, for better visibility and collaboration by the Zulip core team.  I think ultimately we'll want to move this into the `python-zulip-api` project somewhere so one doesn't have to install something extra to use it, but having a staging repository for doing cleanup/extraction before that seems like a good idea.

**Comment by robertylewis** [comment]
Thanks! This all looks good. I'd be very happy to transfer it to the Zulip organization. Is that something I do or you do?

**Comment by timabbott** [comment]
Both: You transfer ownership to a zulip org admin (me) and then I can transfer it into the org.

**Comment by robertylewis** [comment]
Ah, I see. I can't transfer it to you, there's an error: `timabbott/zulip_archive already exists`. I guess one of us will need to rename.

**Comment by timabbott** [comment]
I can delete my fork; the only commits in it are now merged.

**Comment by timabbott** [comment]
OK, done; try again now?

**Comment by robertylewis** [comment]
Okay, you should have a transfer request.

**Comment by timabbott** [comment]
OK, transfer to our fancy new zulip/zulip_archive name complete!  Thanks @robertylewis!

**Comment by robertylewis** [comment]
My pleasure!

**Pull request merged**
